# Generated by Django 5.2.5 on 2025-09-11 13:13

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR')),
                ('positions', models.CharField(choices=[('HC', 'Head Chef'), ('WA', 'Waiter'), ('RM', 'Restaurant Manager'), ('CS', 'Customer Support')], max_length=2)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('message', models.TextField()),
            ],
        ),
    ]
