# Generated by Django 5.2.5 on 2025-09-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employment',
            name='positions',
            field=models.CharField(blank=True, choices=[('HC', 'Head Chef'), ('WA', 'Waiter'), ('RM', 'Restaurant Manager'), ('CS', 'Customer Support')], max_length=2),
        ),
        migrations.AlterField(
            model_name='employment',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
