# Generated by Django 5.2.5 on 2025-09-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_alter_employment_message_alter_employment_positions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='positions',
            field=models.CharField(choices=[('HC', 'Head Chef'), ('WA', 'Waiter'), ('RM', 'Restaurant Manager'), ('CS', 'Customer Support')], max_length=2),
        ),
    ]
