# Generated by Django 5.2 on 2025-05-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_menu_product_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
