# Generated by Django 5.2 on 2025-05-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
